version: '3.3'

services:
  api:
    # image: rshafikov/my_storage:latest
    build: ../api/.
    ports:
      - "5000:5000"
    restart: always
    volumes:
      - my_storage_volume:/app/storage/
    env_file:
      - ./.env

  frontend:
    # image: rshafikov/foodgram-frontend:latest
    build: ../frontend/.
    ports:
      - "80:8000"
    volumes:
      - static:/app/static/

  # nginx:
  #   image: nginx:1.19.3
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/conf.d/default.conf
  #     - static:/var/html/static
  #   restart: always
  #   depends_on:
  #     - api
  #     - frontend

volumes:
  static:
  my_storage_volume:
