version: '3.8'

services:
    
  api:
    build: ../api/.
    # ports:
    #   - "5000:5000"
    restart: always
    volumes:
      - storage_volume:/app/storage/
    env_file:
      - ./.env

  frontend:
    build: ../frontend/.
    restart: always
    volumes:
      - static:/app/static/
    depends_on:
      - api
    env_file:
      - ./.env
  
  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/var/html/static
    restart: always
    depends_on:
      - api
      - frontend

volumes:
  static:
  storage_volume:
